name: Run html and css checker

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Cyb3r-Jak3/html5validator-action@v0.4.2
        with:
          css: true
